# Generated by Django 3.2.12 on 2022-08-25 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qaApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttopic',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentquestion',
            name='course_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code', to='qaApp.studenttopic'),
        ),
        migrations.AddField(
            model_name='studentquestion',
            name='course_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title', to='qaApp.studenttopic'),
        ),
        migrations.AddField(
            model_name='studentquestion',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individualtopic',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indivdualquestion',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indivdualquestion',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qaApp.individualtopic'),
        ),
    ]
