# Generated by Django 3.2.12 on 2022-08-25 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qaApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquestion',
            name='course_title',
            field=models.ForeignKey(db_column='course_title', on_delete=django.db.models.deletion.CASCADE, to='qaApp.studenttopic'),
        ),
    ]
