# Generated by Django 3.2.12 on 2022-08-25 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qaApp', '0003_alter_studentquestion_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquestion',
            name='course_code',
            field=models.ForeignKey(db_column='course_code', on_delete=django.db.models.deletion.CASCADE, related_name='code', to='qaApp.studenttopic'),
        ),
        migrations.AlterField(
            model_name='studentquestion',
            name='course_title',
            field=models.ForeignKey(db_column='course_title', on_delete=django.db.models.deletion.CASCADE, related_name='title', to='qaApp.studenttopic'),
        ),
    ]
