# Generated by Django 3.2.12 on 2022-08-25 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qaApp', '0004_auto_20220826_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentquestion',
            name='course_title',
        ),
        migrations.AlterField(
            model_name='studentquestion',
            name='course_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code', to='qaApp.studenttopic'),
        ),
    ]
